version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCdgSSREBWMdQkkmjq0eqBtfUGilYCCrDQ
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=behavior-dash.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=behavior-dash
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=behavior-dash.firebasestorage.app
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=143027444132
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:143027444132:web:16bd86bbadb3f879808931
    command: npm run dev
    stdin_open: true
    tty: true