version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_FIREBASE_API_KEY=
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=behavior-dash
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
      - NEXT_PUBLIC_FIREBASE_APP_ID=
    command: npm run dev
    stdin_open: true
    tty: true